/**
 * Content library powered by data/vinh_giang.json
 * Generated by the pipeline — no API calls, pure data filtering.
 */
import type { KeyPhrase, VocabularyItem, Framework, Principle, ExampleSentence } from '@/types';

// data/vinh_giang.json lives inside frontend/data/ so webpack can bundle it.
// Static import ensures webpack always bundles the latest file.
import rawData from '../data/vinh_giang.json';

const data: {
  all_phrases: KeyPhrase[];
  all_vocabulary: VocabularyItem[];
  all_frameworks: Framework[];
  all_principles: Principle[];
  all_example_sentences: ExampleSentence[];
  topics_index: Record<string, unknown[]>;
} = {
  all_phrases: rawData.all_phrases ?? [],
  all_vocabulary: rawData.all_vocabulary ?? [],
  all_frameworks: rawData.all_frameworks ?? [],
  all_principles: rawData.all_principles ?? [],
  all_example_sentences: rawData.all_example_sentences ?? [],
  topics_index: rawData.topics_index ?? {},
};

// Normalise data — pipeline may omit id/topic fields
data.all_phrases.forEach((p, i) => {
  if (!p.id) p.id = `phrase-${i}`;
});
data.all_vocabulary.forEach((v, i) => {
  if (!v.id) v.id = `vocab-${i}`;
  if (!v.topic) v.topic = 'general';
});

export function getPhrasesByTopic(topic: string): KeyPhrase[] {
  return data.all_phrases.filter(p => p.topic === topic);
}

export function getVocabularyByTopic(topic: string): VocabularyItem[] {
  return data.all_vocabulary.filter(v => v.topic === topic);
}

export function getFrameworks(topic?: string): Framework[] {
  if (!topic) return data.all_frameworks;
  return data.all_frameworks.filter(f => f.topic === topic);
}

export function getPrinciples(topic?: string): Principle[] {
  if (!topic) return data.all_principles;
  return data.all_principles.filter(p => p.topic === topic);
}

export function getExampleSentences(situation?: string): ExampleSentence[] {
  if (!situation) return data.all_example_sentences;
  const needle = situation.toLowerCase();
  return data.all_example_sentences.filter(e =>
    e.situation.toLowerCase().includes(needle)
  );
}

export function getAllTopics(): string[] {
  return Object.keys(data.topics_index).filter(
    t => (data.topics_index[t] as unknown[]).length > 0
  );
}

export function getItemById(id: string): KeyPhrase | VocabularyItem | null {
  const phrase = data.all_phrases.find(p => p.id === id);
  if (phrase) return phrase;
  const vocab = data.all_vocabulary.find(v => v.id === id);
  return vocab ?? null;
}

export function getPhraseCount(topic: string): number {
  return data.all_phrases.filter(p => p.topic === topic).length;
}

export function getVocabCount(topic: string): number {
  return data.all_vocabulary.filter(v => v.topic === topic).length;
}

// Maps UI context slugs to JSON topic keys.
// Topics present in the data: confidence, vocal_variety, structure, presence,
// vocabulary, communication, connection, other
export const CONTEXT_TO_TOPIC: Record<string, string[]> = {
  'job-interviews':       ['confidence', 'structure', 'vocabulary', 'communication'],
  'church-prayer':        ['presence', 'confidence', 'communication', 'connection'],
  'church-announcements': ['structure', 'presence', 'communication'],
  'presentations':        ['vocal_variety', 'structure', 'presence'],
  'storytelling':         ['vocal_variety', 'presence', 'connection', 'communication'],
  'general':              ['confidence', 'vocal_variety', 'presence', 'other'],
};

export function getPhrasesByContext(context: string): KeyPhrase[] {
  const topics = CONTEXT_TO_TOPIC[context] ?? [];
  return data.all_phrases.filter(p => topics.includes(p.topic));
}

export function getVocabularyByContext(context: string): VocabularyItem[] {
  const topics = CONTEXT_TO_TOPIC[context] ?? [];
  return data.all_vocabulary.filter(v => topics.includes(v.topic));
}

export function getPhraseCountByContext(context: string): number {
  return getPhrasesByContext(context).length;
}

export function getVocabCountByContext(context: string): number {
  return getVocabularyByContext(context).length;
}
