/**
 * Content library powered by data/vinh_giang.json
 * Generated by the pipeline — no API calls, pure data filtering.
 */
import type { KeyPhrase, VocabularyItem, Framework, Principle, ExampleSentence } from '@/types';

// data/vinh_giang.json lives at project root (two levels up from frontend/)
// Next.js resolves this via tsconfig paths or relative import at build time.
// We use a dynamic require with a fallback so the app works before the pipeline runs.
let data: {
  all_phrases: KeyPhrase[];
  all_vocabulary: VocabularyItem[];
  all_frameworks: Framework[];
  all_principles: Principle[];
  all_example_sentences: ExampleSentence[];
  topics_index: Record<string, unknown[]>;
};

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  data = require('../../data/vinh_giang.json');
} catch {
  data = {
    all_phrases: [],
    all_vocabulary: [],
    all_frameworks: [],
    all_principles: [],
    all_example_sentences: [],
    topics_index: {},
  };
}

export function getPhrasesByTopic(topic: string): KeyPhrase[] {
  return data.all_phrases.filter(p => p.topic === topic);
}

export function getVocabularyByTopic(topic: string): VocabularyItem[] {
  return data.all_vocabulary.filter(v => v.topic === topic);
}

export function getFrameworks(topic?: string): Framework[] {
  if (!topic) return data.all_frameworks;
  return data.all_frameworks.filter(f => f.topic === topic);
}

export function getPrinciples(topic?: string): Principle[] {
  if (!topic) return data.all_principles;
  return data.all_principles.filter(p => p.topic === topic);
}

export function getExampleSentences(situation?: string): ExampleSentence[] {
  if (!situation) return data.all_example_sentences;
  const needle = situation.toLowerCase();
  return data.all_example_sentences.filter(e =>
    e.situation.toLowerCase().includes(needle)
  );
}

export function getAllTopics(): string[] {
  return Object.keys(data.topics_index).filter(
    t => (data.topics_index[t] as unknown[]).length > 0
  );
}

export function getItemById(id: string): KeyPhrase | VocabularyItem | null {
  const phrase = data.all_phrases.find(p => p.id === id);
  if (phrase) return phrase;
  const vocab = data.all_vocabulary.find(v => v.id === id);
  return vocab ?? null;
}

export function getPhraseCount(topic: string): number {
  return data.all_phrases.filter(p => p.topic === topic).length;
}

export function getVocabCount(topic: string): number {
  return data.all_vocabulary.filter(v => v.topic === topic).length;
}

// Maps UI context slugs to JSON topic keys
export const CONTEXT_TO_TOPIC: Record<string, string[]> = {
  'job-interviews':       ['confidence', 'structure', 'vocabulary'],
  'church-prayer':        ['prayer_speaking'],
  'church-announcements': ['structure', 'presence'],
  'presentations':        ['storytelling', 'vocal_variety', 'structure'],
  'storytelling':         ['storytelling', 'presence'],
  'general':              ['confidence', 'vocal_variety', 'presence'],
};

export function getPhrasesByContext(context: string): KeyPhrase[] {
  const topics = CONTEXT_TO_TOPIC[context] ?? [];
  return data.all_phrases.filter(p => topics.includes(p.topic));
}

export function getVocabularyByContext(context: string): VocabularyItem[] {
  const topics = CONTEXT_TO_TOPIC[context] ?? [];
  return data.all_vocabulary.filter(v => topics.includes(v.topic));
}

export function getPhraseCountByContext(context: string): number {
  return getPhrasesByContext(context).length;
}

export function getVocabCountByContext(context: string): number {
  return getVocabularyByContext(context).length;
}
